# .github/workflows/ruff.yml
name: Ruff Lint & Format

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
      - "pyproject.toml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.py"
      - "pyproject.toml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 自動コミット用
      pull-requests: write # PR への push 用
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4
        with:
          # PR ブランチに直接 push できるようにする
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      # ---------- pull_request 用：自動整形＆コミット ----------
      - name: Run Ruff formatter (auto-fix)
        if: ${{ github.event_name == 'pull_request' && github.actor != 'github-actions[bot]' }}
        run: ruff format .

      - name: Detect formatting changes
        id: fmt_changed
        if: ${{ github.event_name == 'pull_request' && github.actor != 'github-actions[bot]' }}
        run: |
          if git diff --quiet; then
            echo "changed=false" >>"$GITHUB_OUTPUT"
          else
            echo "changed=true" >>"$GITHUB_OUTPUT"
          fi

      - name: Commit formatted code
        if: ${{ github.event_name == 'pull_request' && steps.fmt_changed.outputs.changed == 'true' }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "style: apply ruff format"
          add: "."
          default_author: github_actions

      # ---------- 共通：Lint と型ヒントチェック ----------
      - name: Ruff lint (all rules)
        run: ruff check .

      - name: Ruff lint (type-hint only, reference)
        run: ruff check . --select ANN --statistics || true
